#!/bin/sh
./MMBlocked50
./MMNaive
./MMRegister
./MMLocalSum
./MMNaive03
./MMUnfolded4
./MMUnfolded2x2
./MMInterchanged
./MMTranspose
./MMBlocked10
./MMBlocked20
./MMBlocked50
./MMBlocked100
./MMBlocked250
./MMBlockedRectangular4-8
./MMBlockedRectangular8-8
./MMBlockedRectangular8-4
./MMBlockedRectangular40-8
./MMRecursive
./MMRecursiveBlocked-4K
./MMRecursiveBlocked-8K
./MMRecursiveBlocked-16K
./MMRecursiveBlocked-32K
./MMRecursiveRectangular4-8
./MMRecursiveRectangular8-8
./MMRecursiveRectangular8-4
./MMRecursiveRectangular40-8
./Sustained
 
